name: CI/CD

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Give gradle executable permission
        run: chmod +x ./gradlew
      - name: Run gradle build
        run: ./gradlew build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/*-all.jar
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
      - name: List Directory
        run: ls